name: Build and Push Docker Image

on:
  push:
    paths:
      - Dockerfile
      - index.html
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout de repository
      - uses: actions/checkout@v4

      # Login naar DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build en push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t 537845ahmed/my-webapp:latest .
          docker push 537845ahmed/my-webapp:latest

